.\Scripts\pyside6-rcc.exe .\resources.qrc -o .\resources_rc.py
.\Scripts\pyside6-rcc.exe  .\Lib\site-packages\qtshared6\resources.qrc -o .\Lib\site-packages\qtshared6\resources.py
.\Scripts\pyside6-uic.exe .\library\ui\dialog.ui -o .\library\ui\dialog.py
.\Scripts\pyside6-uic.exe .\library\ui\expandableTabs.ui -o .\library\ui\expandableTabs.py
.\Scripts\pyside6-uic.exe .\library\ui\asset_delegate.ui -o .\library\ui\asset_delegate.py
.\Scripts\pyside6-uic.exe .\library\ui\list_view_filtered.ui -o .\library\ui\list_view_filtered.py
.\Scripts\pyside6-uic.exe .\library\ui\ingestion.ui -o .\library\ui\ingestion.py
.\Scripts\pyside6-uic.exe .\library\ui\description.ui -o .\library\ui\description.py
.\Scripts\pyside6-uic.exe .\library\ui\compact_delegate.ui -o .\library\ui\compact_delegate.py
C:\Users\Resartist\AppData\Local\Programs\Python\Python37\Scripts\pyside2-uic.exe .\library\plugins\Lib\relic_base\ui\title_bar.ui -o .\library\plugins\Lib\relic_base\ui\title_bar.py
C:\Users\Resartist\AppData\Local\Programs\Python\Python37\Scripts\pyside2-uic.exe .\library\ui\compact_delegate.ui -o .\library\plugins\Lib\relic_base\ui\compact_delegate.py
C:\Users\Resartist\AppData\Local\Programs\Python\Python37\Scripts\pyside2-uic.exe .\library\ui\expandableTabs.ui -o .\library\plugins\Lib\relic_base\ui\expandableTabs.py